//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprosysAccDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_GL
    {
        public int GlId { get; set; }
        public Nullable<int> TranId { get; set; }
        public Nullable<int> TranTypeId { get; set; }
        public Nullable<int> CoaId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityBalance { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<bool> IsGift { get; set; }
        public Nullable<int> FiscarlYear { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<System.DateTime> ActivityTimestamp { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string InvoiceNo { get; set; }
        public string Comments { get; set; }
        public string Misc { get; set; }
        public Nullable<bool> IsPostpaid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> SubscriptionDueDate { get; set; }
        public Nullable<bool> IsSalesCredit { get; set; }
        public Nullable<System.DateTime> CreditPaidDate { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public string DocumentId { get; set; }
    }
}
