//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprosysAccDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_COA
    {
        public int CoaId { get; set; }
        public Nullable<int> PId { get; set; }
        public string CoaNo { get; set; }
        public Nullable<int> HeadAccount { get; set; }
        public string TreeName { get; set; }
        public Nullable<int> CoaLevel { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string ServiceCode { get; set; }
    }
}
