//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprosysAccDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AprosysAccountingEntities : DbContext
    {
        public AprosysAccountingEntities()
            : base("name=AprosysAccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acc_COA> Acc_COA { get; set; }
        public virtual DbSet<Acc_GLTxLinks> Acc_GLTxLinks { get; set; }
        public virtual DbSet<FinancialYear> FinancialYears { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Acc_TransactionTypes> Acc_TransactionTypes { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ReportConfig> ReportConfigs { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<Acc_PartialCredit> Acc_PartialCredit { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<SubscriptionExcludingDate> SubscriptionExcludingDates { get; set; }
        public virtual DbSet<tblinvoice> tblinvoices { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<SalesPerson> SalesPersons { get; set; }
        public virtual DbSet<Acc_GL> Acc_GL { get; set; }
        public virtual DbSet<tblBank> tblBanks { get; set; }
        public virtual DbSet<OilGrade> OilGrades { get; set; }
        public virtual DbSet<Item> Items { get; set; }
    
        public virtual ObjectResult<GetCustomerBalance_Result> GetCustomerBalance(Nullable<int> cstID)
        {
            var cstIDParameter = cstID.HasValue ?
                new ObjectParameter("cstID", cstID) :
                new ObjectParameter("cstID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerBalance_Result>("GetCustomerBalance", cstIDParameter);
        }
    
        public virtual ObjectResult<string> GetLastVoucherNo(Nullable<int> transTypeid)
        {
            var transTypeidParameter = transTypeid.HasValue ?
                new ObjectParameter("transTypeid", transTypeid) :
                new ObjectParameter("transTypeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetLastVoucherNo", transTypeidParameter);
        }
    
        public virtual ObjectResult<GetPaymentVoucherByVoucherNo_Result> GetPaymentVoucherByVoucherNo(string voucherNo)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentVoucherByVoucherNo_Result>("GetPaymentVoucherByVoucherNo", voucherNoParameter);
        }
    
        public virtual ObjectResult<GetReceiptVoucherList_Result> GetReceiptVoucherList(string voucherNo, Nullable<int> typeID, Nullable<System.DateTime> dtStart, Nullable<System.DateTime> dtEnd)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            var typeIDParameter = typeID.HasValue ?
                new ObjectParameter("typeID", typeID) :
                new ObjectParameter("typeID", typeof(int));
    
            var dtStartParameter = dtStart.HasValue ?
                new ObjectParameter("dtStart", dtStart) :
                new ObjectParameter("dtStart", typeof(System.DateTime));
    
            var dtEndParameter = dtEnd.HasValue ?
                new ObjectParameter("dtEnd", dtEnd) :
                new ObjectParameter("dtEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReceiptVoucherList_Result>("GetReceiptVoucherList", voucherNoParameter, typeIDParameter, dtStartParameter, dtEndParameter);
        }
    
        public virtual ObjectResult<GetStockList_Result> GetStockList(Nullable<int> itemID)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("itemID", itemID) :
                new ObjectParameter("itemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockList_Result>("GetStockList", itemIDParameter);
        }
    
        public virtual ObjectResult<GetVendorBalance_Result> GetVendorBalance(Nullable<int> vendID)
        {
            var vendIDParameter = vendID.HasValue ?
                new ObjectParameter("vendID", vendID) :
                new ObjectParameter("vendID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVendorBalance_Result>("GetVendorBalance", vendIDParameter);
        }
    
        public virtual ObjectResult<Report_AccountsPayable_Result> Report_AccountsPayable(Nullable<int> vendorID)
        {
            var vendorIDParameter = vendorID.HasValue ?
                new ObjectParameter("vendorID", vendorID) :
                new ObjectParameter("vendorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_AccountsPayable_Result>("Report_AccountsPayable", vendorIDParameter);
        }
    
        public virtual ObjectResult<Report_CashFlow_Result> Report_CashFlow(Nullable<System.DateTime> dtStart, Nullable<System.DateTime> dtEnd)
        {
            var dtStartParameter = dtStart.HasValue ?
                new ObjectParameter("dtStart", dtStart) :
                new ObjectParameter("dtStart", typeof(System.DateTime));
    
            var dtEndParameter = dtEnd.HasValue ?
                new ObjectParameter("dtEnd", dtEnd) :
                new ObjectParameter("dtEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_CashFlow_Result>("Report_CashFlow", dtStartParameter, dtEndParameter);
        }
    
        public virtual ObjectResult<Report_GetPurchaseInvoice_Result> Report_GetPurchaseInvoice(string voucherNo)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetPurchaseInvoice_Result>("Report_GetPurchaseInvoice", voucherNoParameter);
        }
    
        public virtual ObjectResult<Report_IncomeStatement_Result> Report_IncomeStatement(Nullable<System.DateTime> dtStart, Nullable<System.DateTime> dtEnd)
        {
            var dtStartParameter = dtStart.HasValue ?
                new ObjectParameter("dtStart", dtStart) :
                new ObjectParameter("dtStart", typeof(System.DateTime));
    
            var dtEndParameter = dtEnd.HasValue ?
                new ObjectParameter("dtEnd", dtEnd) :
                new ObjectParameter("dtEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_IncomeStatement_Result>("Report_IncomeStatement", dtStartParameter, dtEndParameter);
        }
    
        public virtual ObjectResult<Report_TrialBalance_Result> Report_TrialBalance(Nullable<System.DateTime> dtStart, Nullable<System.DateTime> dtEnd)
        {
            var dtStartParameter = dtStart.HasValue ?
                new ObjectParameter("dtStart", dtStart) :
                new ObjectParameter("dtStart", typeof(System.DateTime));
    
            var dtEndParameter = dtEnd.HasValue ?
                new ObjectParameter("dtEnd", dtEnd) :
                new ObjectParameter("dtEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_TrialBalance_Result>("Report_TrialBalance", dtStartParameter, dtEndParameter);
        }
    
        public virtual ObjectResult<GetBanksWithBalances_Result> GetBanksWithBalances()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBanksWithBalances_Result>("GetBanksWithBalances");
        }
    
        public virtual ObjectResult<GetStockAlerts_Result> GetStockAlerts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockAlerts_Result>("GetStockAlerts");
        }
    
        public virtual int ResetGL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResetGL");
        }
    
        public virtual int DeletePurchase(string voucherNo, Nullable<int> userID)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePurchase", voucherNoParameter, userIDParameter);
        }
    
        public virtual ObjectResult<GetDailyCashFlow_Result> GetDailyCashFlow(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDailyCashFlow_Result>("GetDailyCashFlow", dateParameter);
        }
    
        public virtual ObjectResult<GetPaymentVoucherList_Result> GetPaymentVoucherList(string voucherNo, Nullable<System.DateTime> dtStart, Nullable<System.DateTime> dtEnd)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            var dtStartParameter = dtStart.HasValue ?
                new ObjectParameter("dtStart", dtStart) :
                new ObjectParameter("dtStart", typeof(System.DateTime));
    
            var dtEndParameter = dtEnd.HasValue ?
                new ObjectParameter("dtEnd", dtEnd) :
                new ObjectParameter("dtEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentVoucherList_Result>("GetPaymentVoucherList", voucherNoParameter, dtStartParameter, dtEndParameter);
        }
    
        public virtual ObjectResult<GetSubscriptionByVoucherNo_Result> GetSubscriptionByVoucherNo(string voucherNo)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubscriptionByVoucherNo_Result>("GetSubscriptionByVoucherNo", voucherNoParameter);
        }
    
        public virtual ObjectResult<GetPurchaseList_Result> GetPurchaseList(Nullable<int> vendorID, Nullable<int> itemID, Nullable<System.DateTime> dtStart, Nullable<System.DateTime> dtEnd)
        {
            var vendorIDParameter = vendorID.HasValue ?
                new ObjectParameter("vendorID", vendorID) :
                new ObjectParameter("vendorID", typeof(int));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("itemID", itemID) :
                new ObjectParameter("itemID", typeof(int));
    
            var dtStartParameter = dtStart.HasValue ?
                new ObjectParameter("dtStart", dtStart) :
                new ObjectParameter("dtStart", typeof(System.DateTime));
    
            var dtEndParameter = dtEnd.HasValue ?
                new ObjectParameter("dtEnd", dtEnd) :
                new ObjectParameter("dtEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPurchaseList_Result>("GetPurchaseList", vendorIDParameter, itemIDParameter, dtStartParameter, dtEndParameter);
        }
    
        public virtual ObjectResult<GetSubscriptionVoucherList_Result> GetSubscriptionVoucherList(string voucherNo, Nullable<System.DateTime> activityStartDate, Nullable<System.DateTime> activityEndDate)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            var activityStartDateParameter = activityStartDate.HasValue ?
                new ObjectParameter("ActivityStartDate", activityStartDate) :
                new ObjectParameter("ActivityStartDate", typeof(System.DateTime));
    
            var activityEndDateParameter = activityEndDate.HasValue ?
                new ObjectParameter("ActivityEndDate", activityEndDate) :
                new ObjectParameter("ActivityEndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubscriptionVoucherList_Result>("GetSubscriptionVoucherList", voucherNoParameter, activityStartDateParameter, activityEndDateParameter);
        }
    
        public virtual ObjectResult<Credit_GetUnpaidCreditSales_Result> Credit_GetUnpaidCreditSales(Nullable<System.DateTime> activityStartDate, Nullable<System.DateTime> activityEndDate)
        {
            var activityStartDateParameter = activityStartDate.HasValue ?
                new ObjectParameter("ActivityStartDate", activityStartDate) :
                new ObjectParameter("ActivityStartDate", typeof(System.DateTime));
    
            var activityEndDateParameter = activityEndDate.HasValue ?
                new ObjectParameter("ActivityEndDate", activityEndDate) :
                new ObjectParameter("ActivityEndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Credit_GetUnpaidCreditSales_Result>("Credit_GetUnpaidCreditSales", activityStartDateParameter, activityEndDateParameter);
        }
    
        public virtual ObjectResult<Credit_GetUnPaidCustomers_Result> Credit_GetUnPaidCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Credit_GetUnPaidCustomers_Result>("Credit_GetUnPaidCustomers");
        }
    
        public virtual int Credit_UpdateUnPaidCreditSales(string invoiceNo, Nullable<int> custID, Nullable<System.DateTime> creditPaidDate, Nullable<int> modifiedBy)
        {
            var invoiceNoParameter = invoiceNo != null ?
                new ObjectParameter("InvoiceNo", invoiceNo) :
                new ObjectParameter("InvoiceNo", typeof(string));
    
            var custIDParameter = custID.HasValue ?
                new ObjectParameter("CustID", custID) :
                new ObjectParameter("CustID", typeof(int));
    
            var creditPaidDateParameter = creditPaidDate.HasValue ?
                new ObjectParameter("CreditPaidDate", creditPaidDate) :
                new ObjectParameter("CreditPaidDate", typeof(System.DateTime));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Credit_UpdateUnPaidCreditSales", invoiceNoParameter, custIDParameter, creditPaidDateParameter, modifiedByParameter);
        }
    
        public virtual ObjectResult<Credit_GetUnPaidCustomersInvoice_Result> Credit_GetUnPaidCustomersInvoice(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Credit_GetUnPaidCustomersInvoice_Result>("Credit_GetUnPaidCustomersInvoice", customerIDParameter);
        }
    
        public virtual ObjectResult<GetSaleInvoiceList_Result> GetSaleInvoiceList(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSaleInvoiceList_Result>("GetSaleInvoiceList", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<GetServiceName_Result> GetServiceName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetServiceName_Result>("GetServiceName");
        }
    
        public virtual ObjectResult<GetReceiptVoucherListByVoucherNO_Result> GetReceiptVoucherListByVoucherNO(string voucherNo, Nullable<int> typeID)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            var typeIDParameter = typeID.HasValue ?
                new ObjectParameter("typeID", typeID) :
                new ObjectParameter("typeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReceiptVoucherListByVoucherNO_Result>("GetReceiptVoucherListByVoucherNO", voucherNoParameter, typeIDParameter);
        }
    
        public virtual ObjectResult<Report_AccountsReceivable_Result> Report_AccountsReceivable(Nullable<int> custID, Nullable<int> typeID)
        {
            var custIDParameter = custID.HasValue ?
                new ObjectParameter("custID", custID) :
                new ObjectParameter("custID", typeof(int));
    
            var typeIDParameter = typeID.HasValue ?
                new ObjectParameter("typeID", typeID) :
                new ObjectParameter("typeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_AccountsReceivable_Result>("Report_AccountsReceivable", custIDParameter, typeIDParameter);
        }
    
        public virtual int Report_BankStatement1(Nullable<int> coaID, Nullable<System.DateTime> beginDate, Nullable<System.DateTime> endDate)
        {
            var coaIDParameter = coaID.HasValue ?
                new ObjectParameter("coaID", coaID) :
                new ObjectParameter("coaID", typeof(int));
    
            var beginDateParameter = beginDate.HasValue ?
                new ObjectParameter("beginDate", beginDate) :
                new ObjectParameter("beginDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Report_BankStatement1", coaIDParameter, beginDateParameter, endDateParameter);
        }
    
        public virtual int Report_BankStatement2(Nullable<int> coaID, Nullable<System.DateTime> beginDate, Nullable<System.DateTime> endDate)
        {
            var coaIDParameter = coaID.HasValue ?
                new ObjectParameter("coaID", coaID) :
                new ObjectParameter("coaID", typeof(int));
    
            var beginDateParameter = beginDate.HasValue ?
                new ObjectParameter("beginDate", beginDate) :
                new ObjectParameter("beginDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Report_BankStatement2", coaIDParameter, beginDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<Report_BankStatement3_Result> Report_BankStatement3(Nullable<int> coaID, Nullable<System.DateTime> beginDate, Nullable<System.DateTime> endDate)
        {
            var coaIDParameter = coaID.HasValue ?
                new ObjectParameter("coaID", coaID) :
                new ObjectParameter("coaID", typeof(int));
    
            var beginDateParameter = beginDate.HasValue ?
                new ObjectParameter("beginDate", beginDate) :
                new ObjectParameter("beginDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_BankStatement3_Result>("Report_BankStatement3", coaIDParameter, beginDateParameter, endDateParameter);
        }
    
        public virtual int Report_BankStatement4(Nullable<int> coaID, Nullable<System.DateTime> beginDate, Nullable<System.DateTime> endDate)
        {
            var coaIDParameter = coaID.HasValue ?
                new ObjectParameter("coaID", coaID) :
                new ObjectParameter("coaID", typeof(int));
    
            var beginDateParameter = beginDate.HasValue ?
                new ObjectParameter("beginDate", beginDate) :
                new ObjectParameter("beginDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Report_BankStatement4", coaIDParameter, beginDateParameter, endDateParameter);
        }
    
        public virtual int Report_BankStatement(Nullable<int> coaID, Nullable<System.DateTime> beginDate, Nullable<System.DateTime> endDate)
        {
            var coaIDParameter = coaID.HasValue ?
                new ObjectParameter("coaID", coaID) :
                new ObjectParameter("coaID", typeof(int));
    
            var beginDateParameter = beginDate.HasValue ?
                new ObjectParameter("beginDate", beginDate) :
                new ObjectParameter("beginDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Report_BankStatement", coaIDParameter, beginDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<Report_WeeklyCashFlow_Result> Report_WeeklyCashFlow(Nullable<System.DateTime> activityTime)
        {
            var activityTimeParameter = activityTime.HasValue ?
                new ObjectParameter("ActivityTime", activityTime) :
                new ObjectParameter("ActivityTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_WeeklyCashFlow_Result>("Report_WeeklyCashFlow", activityTimeParameter);
        }
    
        public virtual ObjectResult<Report_MonthlySubscription_Result> Report_MonthlySubscription(Nullable<int> year, Nullable<int> subsType)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var subsTypeParameter = subsType.HasValue ?
                new ObjectParameter("SubsType", subsType) :
                new ObjectParameter("SubsType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_MonthlySubscription_Result>("Report_MonthlySubscription", yearParameter, subsTypeParameter);
        }
    
        public virtual ObjectResult<GetSubscriptionList_Result> GetSubscriptionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubscriptionList_Result>("GetSubscriptionList");
        }
    
        public virtual ObjectResult<usp_GetSubDuesofCustomer_Result> usp_GetSubDuesofCustomer(Nullable<int> custID)
        {
            var custIDParameter = custID.HasValue ?
                new ObjectParameter("CustID", custID) :
                new ObjectParameter("CustID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSubDuesofCustomer_Result>("usp_GetSubDuesofCustomer", custIDParameter);
        }
    
        public virtual ObjectResult<usp_GetTotalPaidofCustomer_Result> usp_GetTotalPaidofCustomer(Nullable<int> custID)
        {
            var custIDParameter = custID.HasValue ?
                new ObjectParameter("CustID", custID) :
                new ObjectParameter("CustID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetTotalPaidofCustomer_Result>("usp_GetTotalPaidofCustomer", custIDParameter);
        }
    
        public virtual ObjectResult<Report_ItemWiseSale_Result> Report_ItemWiseSale(Nullable<System.DateTime> dtStart, Nullable<System.DateTime> dtEnd)
        {
            var dtStartParameter = dtStart.HasValue ?
                new ObjectParameter("dtStart", dtStart) :
                new ObjectParameter("dtStart", typeof(System.DateTime));
    
            var dtEndParameter = dtEnd.HasValue ?
                new ObjectParameter("dtEnd", dtEnd) :
                new ObjectParameter("dtEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_ItemWiseSale_Result>("Report_ItemWiseSale", dtStartParameter, dtEndParameter);
        }
    
        public virtual ObjectResult<Report_GetSaleInvoice_Result> Report_GetSaleInvoice(string voucherNo)
        {
            var voucherNoParameter = voucherNo != null ?
                new ObjectParameter("voucherNo", voucherNo) :
                new ObjectParameter("voucherNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetSaleInvoice_Result>("Report_GetSaleInvoice", voucherNoParameter);
        }
    }
}
