//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprosysAccDB
{
    using System;
    
    public partial class GetSaleInvoiceList_Result1
    {
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> ActivityTimestamp { get; set; }
        public string cstName { get; set; }
        public Nullable<decimal> NETAMOUNT { get; set; }
        public decimal PAID { get; set; }
        public Nullable<decimal> BAL { get; set; }
        public int IsDeletable { get; set; }
    }
}
