//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprosysAccDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionExcludingDate
    {
        public int Id { get; set; }
        public int CustId { get; set; }
        public Nullable<System.DateTime> SubDisableStartDate { get; set; }
        public Nullable<System.DateTime> SubDisableEndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
